# Generated by Django 3.0.7 on 2020-09-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('', 'Please select'), ('admin', 'Admin')], max_length=100, verbose_name='What is your primary role in platform?'),
        ),
    ]
