# Generated by Django 3.0.7 on 2020-09-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='default_logos')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='school_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('app_join', models.CharField(choices=[('', 'Please select'), ('form_one', 'Form 1'), ('form_two', 'Form 2'), ('form_three', 'Form 3'), ('form_five', 'Form 5')], max_length=100, verbose_name='Application to Join')),
                ('name', models.CharField(max_length=150, verbose_name='Student Name')),
                ('index_no', models.CharField(blank=True, max_length=150, verbose_name='Index Number')),
                ('parent_name', models.CharField(max_length=150, verbose_name='Parent/Guardian Name')),
                ('form_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Form Number')),
                ('app_date', models.DateField(verbose_name='Application Date')),
                ('interview_date', models.DateField(blank=True, null=True, verbose_name='Interview Date')),
                ('passport', models.ImageField(upload_to='student_passport', verbose_name='Student Passport')),
                ('last_school', models.CharField(max_length=200, verbose_name='Last Attended School name')),
                ('school_contact', models.CharField(max_length=150, verbose_name='School Contacts')),
                ('birthdate', models.DateField(verbose_name="Student's Date of Birth")),
                ('gender', models.CharField(choices=[('', 'Please select'), ('male', 'Male'), ('female', 'Female')], max_length=100, verbose_name='Student Gender')),
                ('residence', models.CharField(max_length=200, verbose_name="Student's Place of Residence")),
                ('parent_contact', models.CharField(max_length=200, verbose_name='Parent Contacts Details')),
                ('payment_reference_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='App.Fee Payment Ref No')),
                ('app_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Applicant ID')),
                ('special_requirements', models.CharField(choices=[('', 'Please select'), ('none', 'None'), ('visual_impairment', 'Visual Impairments'), ('hearing_impairment', 'Hearing Impairment'), ('physical_impairment', 'Physical Impairement'), ('other', 'Other')], max_length=150, verbose_name="Student's special requirements")),
                ('f21c_contact', models.CharField(default='0758000090', editable=False, max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.School', verbose_name='School Name')),
            ],
        ),
    ]
