# Generated by Django 3.0.7 on 2020-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200913_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Tick to mark Paid'),
        ),
    ]
