# Generated by Django 3.0.7 on 2020-09-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200913_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='f21c_contact',
            field=models.CharField(default='0758000090', max_length=50),
        ),
    ]
