# Generated by Django 3.0.7 on 2020-09-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200913_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='app_join',
            field=models.CharField(choices=[('', 'Please select'), ('form one', 'Form One'), ('form five', 'Form Five'), ('transfer form one', 'Transfer form one'), ('transfer form five', 'Transfer form one')], max_length=100, verbose_name='Application to Join'),
        ),
    ]
