# Generated by Django 3.0.7 on 2020-09-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200916_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='app_join',
            field=models.CharField(choices=[('', 'Please select'), ('form one', 'Form one'), ('form five', 'Form five'), ('transfer form one', 'Transfer form one'), ('transfer form three', 'Transfer form three'), ('transfer form five', 'Transfer form five')], max_length=100, verbose_name='Application to Join'),
        ),
    ]
