# Generated by Django 3.0.7 on 2020-09-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200917_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.School')),
            ],
        ),
    ]
