# Generated by Django 3.0.7 on 2020-09-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200918_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfee',
            name='form',
            field=models.CharField(choices=[('', 'Please select'), ('form one', 'Form one'), ('form five', 'Form five'), ('transfer form one', 'Transfer form one'), ('transfer form three', 'Transfer form three'), ('transfer form five', 'Transfer form five')], max_length=100),
        ),
    ]
