# Generated by Django 3.0.7 on 2020-09-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200918_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfee',
            name='fee',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Application Fee'),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='form',
            field=models.CharField(choices=[('', 'Please select'), ('form one', 'Form one'), ('form five', 'Form five'), ('transfer form one', 'Transfer form one'), ('transfer form three', 'Transfer form three'), ('transfer form five', 'Transfer form five')], max_length=100, verbose_name='Application to Join'),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.School', verbose_name='Select the school'),
        ),
    ]
