# Generated by Django 3.0.7 on 2020-12-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201224_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfee',
            name='form',
            field=models.CharField(choices=[('', 'Please select'), ('Form one', 'Form one'), ('Form five', 'Form five'), ('Transfer form one', 'Transfer form one'), ('Transfer form three', 'Transfer form three'), ('Transfer form five', 'Transfer form five')], max_length=100, verbose_name='Application to Join'),
        ),
    ]
